// resources/js/components/ui/Progress.vue
<script setup>
import { computed } from 'vue';

const props = defineProps({
    value: { type: Number, default: 0 },
    max: { type: Number, default: 100 },
    label: { type: String, default: null },
    indeterminate: { type: Boolean, default: false },
    size: { type: String, default: 'md' },
});

const sizes = {
    sm: 'h-1',
    md: 'h-1.5',
    lg: 'h-2.5',
};

const percent = computed(() => (props.max > 0 ? Math.min(100, Math.max(0, (props.value / props.max) * 100)) : 0));
</script>

<template>
    <div class="w-full">
        <div v-if="label" class="mb-2 flex items-baseline justify-between gap-4">
            <span class="text-xs text-zinc-500">{{ label }}</span>
            <span v-if="!indeterminate" class="font-mono text-xs text-jade-400">{{ Math.round(percent) }}%</span>
        </div>
        <div
            role="progressbar"
            aria-valuemin="0"
            :aria-valuemax="max"
            :aria-valuenow="indeterminate ? undefined : value"
            :aria-label="label ?? undefined"
            class="overflow-hidden rounded-full bg-ink-800"
            :class="sizes[size] ?? sizes.md"
        >
            <div v-if="indeterminate" class="h-full w-1/3 rounded-full bg-jade-500 animate-[ui-progress-slide_1.4s_ease-in-out_infinite]"></div>
            <div v-else class="h-full rounded-full bg-jade-500 transition-[width] duration-500 ease-snap" :style="{ width: percent + '%' }"></div>
        </div>
    </div>
</template>

<style>
@keyframes ui-progress-slide {
    from {
        translate: -150% 0;
    }

    to {
        translate: 400% 0;
    }
}
</style>

// resources/js/components/ui/Progress.jsx
const sizes = {
    sm: 'h-1',
    md: 'h-1.5',
    lg: 'h-2.5',
};

export function UiProgress({
    value = 0,
    max = 100,
    label = null,
    indeterminate = false,
    size = 'md',
    className = '',
    ...props
}) {
    const percent = max > 0 ? Math.min(100, Math.max(0, (value / max) * 100)) : 0;

    return (
        <div className={`w-full ${className}`.trim()} {...props}>
            <style>{'@keyframes ui-progress-slide { from { translate: -150% 0; } to { translate: 400% 0; } }'}</style>
            {label && (
                <div className="mb-2 flex items-baseline justify-between gap-4">
                    <span className="text-xs text-zinc-500">{label}</span>
                    {!indeterminate && <span className="font-mono text-xs text-jade-400">{Math.round(percent)}%</span>}
                </div>
            )}
            <div
                role="progressbar"
                aria-valuemin={0}
                aria-valuemax={max}
                aria-valuenow={indeterminate ? undefined : value}
                aria-label={label ?? undefined}
                className={`overflow-hidden rounded-full bg-ink-800 ${sizes[size] ?? sizes.md}`}
            >
                {indeterminate ? (
                    <div className="h-full w-1/3 rounded-full bg-jade-500 animate-[ui-progress-slide_1.4s_ease-in-out_infinite]" />
                ) : (
                    <div className="h-full rounded-full bg-jade-500 transition-[width] duration-500 ease-snap" style={{ width: `${percent}%` }} />
                )}
            </div>
        </div>
    );
}
