// resources/js/components/ui/data-display/Separator.vue
<script setup>
defineProps({
    label: { type: String, default: null },
    vertical: { type: Boolean, default: false },
});
</script>

<template>
    <span v-if="vertical" class="inline-block w-px self-stretch bg-white/10"></span>
    <div v-else-if="label !== null" class="flex w-full items-center gap-3">
        <span class="h-px flex-1 bg-white/10"></span>
        <span class="font-mono text-[10px] tracking-wider text-zinc-600 uppercase">{{ label }}</span>
        <span class="h-px flex-1 bg-white/10"></span>
    </div>
    <div v-else class="h-px w-full bg-white/10"></div>
</template>

// resources/js/components/ui/Separator.jsx
export function UiSeparator({ label = null, vertical = false, className = '', ...props }) {
    if (vertical) {
        return <span className={['inline-block w-px self-stretch bg-white/10', className].filter(Boolean).join(' ')} {...props} />;
    }

    if (label !== null) {
        return (
            <div className={['flex w-full items-center gap-3', className].filter(Boolean).join(' ')} {...props}>
                <span className="h-px flex-1 bg-white/10" />
                <span className="font-mono text-[10px] tracking-wider text-zinc-600 uppercase">{label}</span>
                <span className="h-px flex-1 bg-white/10" />
            </div>
        );
    }

    return <div className={['h-px w-full bg-white/10', className].filter(Boolean).join(' ')} {...props} />;
}
