// resources/js/components/ui/panels/Toolbar.jsx
export function UiToolbar({ start = null, center = null, end = null, className = '', ...props }) {
    const classes = ['flex items-center justify-between gap-2 rounded-xl border border-white/10 bg-ink-800 p-1.5', className].filter(Boolean).join(' ');

    return (
        <div className={classes} role="toolbar" {...props}>
            {start && <div className="flex items-center gap-1">{start}</div>}
            {center && <div className="flex items-center gap-1">{center}</div>}
            {end && <div className="flex items-center gap-1.5">{end}</div>}
        </div>
    );
}

// resources/js/components/ui/Toolbar.vue
<script setup>
import { useSlots } from 'vue';

const slots = useSlots();
</script>

<template>
    <div class="flex items-center justify-between gap-2 rounded-xl border border-white/10 bg-ink-800 p-1.5" role="toolbar">
        <div v-if="slots.start" class="flex items-center gap-1"><slot name="start" /></div>
        <div v-if="slots.center" class="flex items-center gap-1"><slot name="center" /></div>
        <div v-if="slots.end" class="flex items-center gap-1.5"><slot name="end" /></div>
    </div>
</template>
