// resources/js/components/ui/Marquee.jsx
const keyframes = `
@keyframes ui-marquee-x { to { transform: translateX(-50%); } }
@keyframes ui-marquee-y { to { transform: translateY(-50%); } }
@media (prefers-reduced-motion: reduce) { [class*='ui-marquee-'] { animation: none; } }
`;

export function UiMarquee({
    speed = 20,
    reverse = false,
    vertical = false,
    gap = 'gap-3',
    pauseOnHover = true,
    fade = true,
    className = '',
    children,
    ...props
}) {
    const rootClasses = [
        'group relative overflow-hidden',
        vertical ? 'flex' : '',
        fade
            ? vertical
                ? '[mask-image:linear-gradient(to_bottom,transparent,black_12%,black_88%,transparent)]'
                : '[mask-image:linear-gradient(to_right,transparent,black_12%,black_88%,transparent)]'
            : '',
        className,
    ]
        .filter(Boolean)
        .join(' ');

    const trackClasses = [
        'flex',
        vertical
            ? 'flex-col h-max animate-[ui-marquee-y_var(--ui-marquee-speed)_linear_infinite]'
            : 'w-max animate-[ui-marquee-x_var(--ui-marquee-speed)_linear_infinite]',
        reverse ? '[animation-direction:reverse]' : '',
        pauseOnHover ? 'group-hover:[animation-play-state:paused]' : '',
    ]
        .filter(Boolean)
        .join(' ');

    const groupClasses = ['flex shrink-0', vertical ? 'flex-col pb-3' : 'pr-3', gap].filter(Boolean).join(' ');

    return (
        <div className={rootClasses} style={{ '--ui-marquee-speed': `${Math.max(1, speed)}s` }} {...props}>
            <style>{keyframes}</style>
            <div className={trackClasses}>
                <div className={groupClasses}>{children}</div>
                <div className={groupClasses} aria-hidden="true">
                    {children}
                </div>
            </div>
        </div>
    );
}

// resources/js/components/ui/effects/Marquee.vue
<script setup>
import { computed } from 'vue';

const props = defineProps({
    speed: { type: Number, default: 20 },
    reverse: { type: Boolean, default: false },
    vertical: { type: Boolean, default: false },
    gap: { type: String, default: 'gap-3' },
    pauseOnHover: { type: Boolean, default: true },
    fade: { type: Boolean, default: true },
});

const rootClasses = computed(() => [
    'group relative overflow-hidden',
    props.vertical ? 'flex' : '',
    props.fade
        ? props.vertical
            ? '[mask-image:linear-gradient(to_bottom,transparent,black_12%,black_88%,transparent)]'
            : '[mask-image:linear-gradient(to_right,transparent,black_12%,black_88%,transparent)]'
        : '',
]);

const trackClasses = computed(() => [
    'flex',
    props.vertical
        ? 'flex-col h-max animate-[ui-marquee-y_var(--ui-marquee-speed)_linear_infinite]'
        : 'w-max animate-[ui-marquee-x_var(--ui-marquee-speed)_linear_infinite]',
    props.reverse ? '[animation-direction:reverse]' : '',
    props.pauseOnHover ? 'group-hover:[animation-play-state:paused]' : '',
]);

const groupClasses = computed(() => [
    'flex shrink-0',
    props.vertical ? 'flex-col pb-3' : 'pr-3',
    props.gap,
]);
</script>

<template>
    <div :class="rootClasses" :style="{ '--ui-marquee-speed': `${Math.max(1, speed)}s` }">
        <div :class="trackClasses">
            <div :class="groupClasses"><slot /></div>
            <div :class="groupClasses" aria-hidden="true"><slot /></div>
        </div>
    </div>
</template>

<style>
@keyframes ui-marquee-x {
    to {
        transform: translateX(-50%);
    }
}

@keyframes ui-marquee-y {
    to {
        transform: translateY(-50%);
    }
}

@media (prefers-reduced-motion: reduce) {
    [class*='ui-marquee-'] {
        animation: none;
    }
}
</style>
