// resources/js/templates/inbox/Shell.vue
<script setup>
import InboxAvatar from './Avatar.vue';
import UiScrollTop from '../../components/ui/navigation/ScrollTop.vue';

defineProps({
    active: { type: String, default: 'Inbox' },
    folder: { type: String, default: 'Unassigned' },
    rail: { type: Boolean, default: true },
    padded: { type: Boolean, default: true },
    promise: { type: String, default: '4h first reply, business hours GMT+8' },
});

const links = [
    { label: 'Inbox', screen: 'threads' },
    { label: 'Compose', screen: 'compose' },
    { label: 'Search', screen: 'search' },
];

const folders = [
    { label: 'Unassigned', count: 3, urgent: true },
    { label: 'Mine', count: 3, urgent: false },
    { label: 'Waiting on them', count: 1, urgent: false },
    { label: 'Snoozed', count: 1, urgent: false },
];

const lanes = [
    { label: 'Warranty', count: 2 },
    { label: 'Dealers', count: 3 },
    { label: 'Orders', count: 2 },
    { label: 'Parts', count: 1 },
];

const desk = ['Hana Okabe', 'Lena Kohler', 'Idris Bahar'];
</script>

<template>
    <div class="flex h-full w-full flex-col overflow-hidden bg-ink-950">
        <header class="shrink-0 border-b border-white/5 bg-ink-950">
            <div class="flex h-14 items-center gap-5 px-4 sm:px-5">
                <a href="/templates/inbox/screens/threads" target="_top" class="flex shrink-0 items-center gap-2.5">
                    <svg class="size-6 text-jade-400" viewBox="0 0 24 24" fill="none">
                        <path d="M3.5 8.5 12 14l8.5-5.5M3.5 6.5h17v11h-17z" stroke="currentColor" stroke-width="1.4" stroke-linejoin="round"/>
                    </svg>
                    <span class="flex flex-col leading-none">
                        <span class="text-sm font-medium tracking-tight text-cream">Front desk</span>
                        <span class="mt-0.5 font-mono text-[10px] text-zinc-600">support@nomadsupply.cc</span>
                    </span>
                </a>

                <nav class="hidden items-center gap-1 md:flex">
                    <a
                        v-for="link in links"
                        :key="link.label"
                        :href="`/templates/inbox/screens/${link.screen}`"
                        target="_top"
                        :aria-current="link.label === active ? 'page' : undefined"
                        class="rounded-lg px-2.5 py-1.5 text-[13px] transition-colors duration-150 outline-none focus-visible:ring-2 focus-visible:ring-jade-500/70"
                        :class="link.label === active ? 'bg-white/8 text-cream' : 'text-zinc-500 hover:bg-white/5 hover:text-cream'"
                    >{{ link.label }}</a>
                </nav>

                <div class="ml-auto flex shrink-0 items-center gap-3">
                    <span class="hidden items-center gap-1.5 rounded-lg border border-red-400/40 bg-red-500/8 px-2.5 py-1.5 font-mono text-[11px] text-red-300 lg:flex">
                        <span class="size-1.5 rounded-full bg-red-400"></span>
                        2 past the promise
                    </span>

                    <div class="hidden items-center -space-x-1.5 sm:flex">
                        <InboxAvatar v-for="person in desk" :key="person" :name="person" size="sm" class="ring-2 ring-ink-950" />
                    </div>

                    <button
                        type="button"
                        class="inline-flex items-center gap-1.5 rounded-lg bg-jade-500 px-3 py-1.5 text-[13px] font-medium text-ink-950 transition-colors duration-150 outline-none hover:bg-jade-400 focus-visible:ring-2 focus-visible:ring-jade-500/70"
                    >
                        <svg class="size-3.5" viewBox="0 0 16 16" fill="none"><path d="M8 3.5v9M3.5 8h9" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"/></svg>
                        Write
                    </button>
                </div>
            </div>

            <div v-if="$slots.toolbar" class="border-t border-white/5 px-4 py-2.5 sm:px-5">
                <slot name="toolbar" />
            </div>
        </header>

        <div class="relative flex min-h-0 flex-1">
            <aside v-if="rail" class="hidden w-52 shrink-0 flex-col justify-between overflow-y-auto border-r border-white/5 py-4 lg:flex">
                <div>
                    <p class="px-4 font-mono text-[10px] tracking-wider text-zinc-700 uppercase">Queues</p>
                    <nav class="mt-2 px-2">
                        <a
                            v-for="entry in folders"
                            :key="entry.label"
                            href="/templates/inbox/screens/threads"
                            target="_top"
                            :aria-current="entry.label === folder ? 'page' : undefined"
                            class="flex items-center gap-2 rounded-lg px-2 py-1.5 text-[13px] transition-colors duration-150 outline-none focus-visible:ring-2 focus-visible:ring-jade-500/70"
                            :class="entry.label === folder ? 'bg-white/8 text-cream' : 'text-zinc-500 hover:bg-white/5 hover:text-cream'"
                        >
                            <span class="truncate">{{ entry.label }}</span>
                            <span class="ml-auto shrink-0 font-mono text-[10px]" :class="entry.urgent ? 'text-red-300' : 'text-zinc-600'">{{ entry.count }}</span>
                        </a>
                    </nav>

                    <p class="mt-6 px-4 font-mono text-[10px] tracking-wider text-zinc-700 uppercase">Lanes</p>
                    <nav class="mt-2 px-2">
                        <a
                            v-for="lane in lanes"
                            :key="lane.label"
                            href="/templates/inbox/screens/search"
                            target="_top"
                            class="flex items-center gap-2 rounded-lg px-2 py-1.5 text-[13px] text-zinc-500 transition-colors duration-150 outline-none hover:bg-white/5 hover:text-cream focus-visible:ring-2 focus-visible:ring-jade-500/70"
                        >
                            <span class="truncate">{{ lane.label }}</span>
                            <span class="ml-auto shrink-0 font-mono text-[10px] text-zinc-600">{{ lane.count }}</span>
                        </a>
                    </nav>
                </div>

                <div class="mx-2 mt-6 rounded-xl border border-white/8 bg-ink-900 p-3">
                    <p class="font-mono text-[10px] text-zinc-600">Reply promise</p>
                    <p class="mt-1.5 text-[12px]/5 text-zinc-400">{{ promise }}</p>
                    <div class="mt-2.5 flex items-center gap-2">
                        <span class="block h-0.5 flex-1 overflow-hidden rounded-full bg-white/10">
                            <span class="block h-full w-[82%] rounded-full bg-jade-500/70"></span>
                        </span>
                        <span class="font-mono text-[10px] text-zinc-500">82%</span>
                    </div>
                    <p class="mt-1.5 font-mono text-[10px] text-zinc-700">kept, last 30 days</p>
                </div>
            </aside>

            <main v-if="padded" data-ui-scroll-region class="min-h-0 flex-1 overflow-y-auto px-4 py-6 sm:px-5">
                <slot />
            </main>
            <main v-else class="flex min-h-0 flex-1 flex-col overflow-hidden">
                <slot />
            </main>

            <UiScrollTop v-if="padded" anchor="container" variant="progress" :threshold="300" />
        </div>
    </div>
</template>

// resources/js/templates/faq/Shell.jsx
import { UiScrollTop } from '../../components/ui/navigation/ScrollTop';

const LINKS = [
    { label: 'Answers', screen: 'questions' },
    { label: 'Ask', screen: 'ask' },
    { label: 'Editing', screen: 'editing' },
];

const TOPICS = [
    { label: 'Noise and grind', count: 4, hot: true },
    { label: 'Setting it up', count: 3, hot: false },
    { label: 'Warranty', count: 3, hot: false },
    { label: 'Orders and delivery', count: 3, hot: false },
    { label: 'Before you buy', count: 2, hot: false },
    { label: 'Dealers', count: 1, hot: false },
];

const ELSEWHERE = [
    { label: 'The manual, as a PDF', meta: '2.4 MB' },
    { label: 'Spare parts list', meta: '48 items' },
    { label: 'Workshop notes', meta: 'blog' },
];

export function FaqShell({ active = 'Answers', topic = null, rail = true, padded = true, toolbar = null, children }) {
    return (
        <div className="flex h-full w-full flex-col overflow-hidden bg-ink-950">
            <header className="shrink-0 border-b border-white/5 bg-ink-950">
                <div className="flex h-14 items-center gap-5 px-4 sm:px-5">
                    <a href="/templates/faq/screens/questions" target="_top" className="flex shrink-0 items-center gap-2.5">
                        <svg className="size-6 text-jade-400" viewBox="0 0 24 24" fill="none">
                            <path d="M4 5.5h7a2 2 0 0 1 2 2v11a2 2 0 0 0-2-2H4zM20 5.5h-7a2 2 0 0 0-2 2v11a2 2 0 0 1 2-2h7z" stroke="currentColor" strokeWidth="1.4" strokeLinejoin="round"/>
                        </svg>
                        <span className="flex flex-col leading-none">
                            <span className="text-sm font-medium tracking-tight text-cream">Help centre</span>
                            <span className="mt-0.5 font-mono text-[10px] text-zinc-600">help.nomadsupply.cc</span>
                        </span>
                    </a>

                    <nav className="hidden items-center gap-1 md:flex">
                        {LINKS.map((link) => (
                            <a
                                key={link.label}
                                href={`/templates/faq/screens/${link.screen}`}
                                target="_top"
                                aria-current={link.label === active ? 'page' : undefined}
                                className={`rounded-lg px-2.5 py-1.5 text-[13px] transition-colors duration-150 outline-none focus-visible:ring-2 focus-visible:ring-jade-500/70 ${
                                    link.label === active ? 'bg-white/8 text-cream' : 'text-zinc-500 hover:bg-white/5 hover:text-cream'
                                }`}
                            >
                                {link.label}
                            </a>
                        ))}
                    </nav>

                    <div className="ml-auto flex shrink-0 items-center gap-3">
                        <span className="hidden items-center gap-1.5 font-mono text-[11px] text-zinc-600 lg:flex">
                            <span className="size-1.5 rounded-full bg-jade-400"></span>
                            16 answers · last edited yesterday
                        </span>

                        <a
                            href="/templates/faq/screens/ask"
                            target="_top"
                            className="inline-flex items-center gap-1.5 rounded-lg bg-jade-500 px-3 py-1.5 text-[13px] font-medium text-ink-950 transition-colors duration-150 outline-none hover:bg-jade-400 focus-visible:ring-2 focus-visible:ring-jade-500/70"
                        >
                            Ask a person
                        </a>
                    </div>
                </div>

                {toolbar && <div className="border-t border-white/5 px-4 py-2.5 sm:px-5">{toolbar}</div>}
            </header>

            <div className="relative flex min-h-0 flex-1">
                {rail && (
                    <aside className="hidden w-56 shrink-0 flex-col justify-between overflow-y-auto border-r border-white/5 py-4 lg:flex">
                        <div>
                            <p className="px-4 font-mono text-[10px] tracking-wider text-zinc-700 uppercase">Headings</p>
                            <nav className="mt-2 px-2">
                                {TOPICS.map((entry) => (
                                    <a
                                        key={entry.label}
                                        href="/templates/faq/screens/questions"
                                        target="_top"
                                        aria-current={entry.label === topic ? 'page' : undefined}
                                        className={`flex items-center gap-2 rounded-lg px-2 py-1.5 text-[13px] transition-colors duration-150 outline-none focus-visible:ring-2 focus-visible:ring-jade-500/70 ${
                                            entry.label === topic ? 'bg-white/8 text-cream' : 'text-zinc-500 hover:bg-white/5 hover:text-cream'
                                        }`}
                                    >
                                        <span className="truncate">{entry.label}</span>
                                        {entry.hot && <span className="size-1 shrink-0 rounded-full bg-jade-400/70"></span>}
                                        <span className="ml-auto shrink-0 font-mono text-[10px] text-zinc-700">{entry.count}</span>
                                    </a>
                                ))}
                            </nav>

                            <p className="mt-6 px-4 font-mono text-[10px] tracking-wider text-zinc-700 uppercase">Elsewhere</p>
                            <nav className="mt-2 px-2">
                                {ELSEWHERE.map((link) => (
                                    <a
                                        key={link.label}
                                        href="/templates/faq/screens/answer"
                                        target="_top"
                                        className="flex items-center gap-2 rounded-lg px-2 py-1.5 text-[13px] text-zinc-500 transition-colors duration-150 outline-none hover:bg-white/5 hover:text-cream focus-visible:ring-2 focus-visible:ring-jade-500/70"
                                    >
                                        <span className="truncate">{link.label}</span>
                                        <span className="ml-auto shrink-0 font-mono text-[10px] text-zinc-700">{link.meta}</span>
                                    </a>
                                ))}
                            </nav>
                        </div>

                        <div className="mx-2 mt-6 rounded-xl border border-white/8 bg-ink-900 p-3">
                            <p className="font-mono text-[10px] text-zinc-600">If none of this helps</p>
                            <p className="mt-1.5 text-[12px]/5 text-zinc-400">Four people read the mail. One of them built your grinder.</p>
                            <div className="mt-2.5 flex items-baseline gap-1.5">
                                <span className="font-mono text-lg text-cream">47</span>
                                <span className="font-mono text-[10px] text-zinc-600">min median first reply</span>
                            </div>
                            <a
                                href="/templates/faq/screens/ask"
                                target="_top"
                                className="mt-2.5 block rounded-lg border border-white/10 py-1.5 text-center text-[12px] text-zinc-300 transition-colors duration-150 hover:border-jade-500/60 hover:text-cream"
                            >
                                Write to the desk
                            </a>
                        </div>
                    </aside>
                )}

                {padded ? (
                    <main data-faq-scroll data-ui-scroll-region className="min-h-0 flex-1 overflow-y-auto px-4 py-6 sm:px-5">{children}</main>
                ) : (
                    <main className="flex min-h-0 flex-1 flex-col overflow-hidden">{children}</main>
                )}

                {padded && <UiScrollTop anchor="container" variant="progress" threshold={300} />}
            </div>
        </div>
    );
}
